machine_mgt:
  build: .
  environment:
    ENV: "DEV"
  volumes:
    - .:/usr/src/app
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  links:
    - machine_mgt
